version: '3.8'
services:
  postgres:
    image: db
    container_name: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
    - .env
    networks:
      - backend  
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: app     
    build:
      context: ./app
      dockerfile: Dockerfile   
    expose:
      - 5000
    env_file:
    - .env      
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
    scale: 3

  proxy:
    image: proxy
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - app

networks:
  backend:
    ipam:      
      config:
        - subnet: 10.10.20.0/24
          gateway: 10.10.20.1
  frontend:
    ipam:      
      config:
        - subnet: 10.10.10.0/24 
          gateway: 10.10.10.1         
          
volumes:
  db_data:



  