apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  ports:    
    - port: 5000
      targetPort: 5000
  selector:
    app: app  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:      
      labels:
        app: app
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env            
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env            
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db                         
          image: public.ecr.aws/o5j9v9p7/app:latest
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits: 
              memory: "200Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /app_health_check
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 2       
          readinessProbe:
            httpGet:
              path: /app_health_check
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3              
              
      
